Campus/Models/Collection.cs
using System.ComponentModel.DataAnnotations;

namespace Campus.Models
{



    /// <summary>
    /// 收藏表
    /// </summary>

    public class Collection
    {
        public int CollectionId { get; set; }

        public string UserId { get; set; }

        public virtual AppUser User { get; set; }

        public int WorksId { get; set; }

        public virtual Works Works { get; set; }
    }



}

Campus/Models/Comment.cs
using System.ComponentModel.DataAnnotations;

namespace Campus.Models
{



    /// <summary>
    /// 评论表
    /// </summary>
    public class Comment
    {
        [Key]
        public int CommentId { get; set; }

        public int? WorksId { get; set; }

        public string UserId { get; set; }

        public string Content { get; set; }

        public int? Parentid { get; set; }

        public DateTime ReleaseTime { get; set; }

        public int Like { get; set; }

        public virtual AppUser User { get; set; }

        public virtual Works Works { get; set; }

        public virtual Comment TComment { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
    }



}

Campus/ViewModels/CommentViewModel.cs
using Campus.Models;

namespace Campus.ViewModels
{
    public class CommentViewModel
    {
        public string HeadPortrait { get; set; }
        public int WorksId { get; set; }

        public int? Parentid { get; set; }
        public IEnumerable<Comment> Comments { get; set; }


    }
}

Campus/Controllers/SpaceController.cs
using Campus.Infrastructure;
using Campus.Models;
using Campus.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace Campus.Controllers
{
    public class SpaceController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly RoleManager<IdentityRole> _RoleManager;
        private readonly CampusDbContext _campusDbContext;
        private readonly IWebHostEnvironment _webHostEnvironment;


        public SpaceController(UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager,
            RoleManager<IdentityRole> roleManager,
            CampusDbContext campusDbContext,
            IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _RoleManager = roleManager;
            _campusDbContext = campusDbContext;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet("{controller}")]
        public async Task<IActionResult> SpaceBase()
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                var user = await _userManager.GetUserAsync(User);
                return RedirectToAction("SpaceBase", new { id = user.Id });
            }
            return RedirectToAction("login", "account");
        }

        [HttpGet("{controller}/{id}")]
        public async Task<IActionResult> SpaceBase(string id)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();
            var model = new SpaceViewModel
            {
                HeadPortrait = user.HeadPortrait,
                Nickname = user.Nickname,
                PersonalSignature = user.PersonalSignature,
                Gender = user.Gender.GenderValue,
                FollowsCount = user.Follows.Count,
                TargetsCount = user.Targets.Count
            };
            var roleList = await _userManager.GetRolesAsync(user);
            if (roleList == null || roleList.Count == 0)
            {
                model.Role = "游客";
            }
            else
            {
                model.Role = roleList[0];
            }
            ViewBag.Title = user.Nickname + "的个人空间";
            ViewBag.Id = id;
            return View(model);
        }

        [HttpGet("{controller}/{action}")]
        public async Task<IActionResult> MyPosts(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
                return Redirect("error/404");
            return View(user.Works
                .Where(w => w.IsDelete == false)
                .OrderByDescending(w => w.ReleaseTime)
                .Select(w => new
                {
                    w.WorksId,
                    w.Title,
                    FabulousCount = w.Fabulous.Count,
                    CollectionsCount = w.Collections.Count,
                    w.Browse,
                    ReleaseTime = w.ReleaseTime.ToString("yyyy年MM月dd日HH时mm分")
                })
                .ToList());
        }

        [Authorize]
        [HttpGet("{controller}/setting/{action}")]
        public async Task<IActionResult> Info()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var model = new SpaceSettingInfoViewModel
            {
                Birth = user.Birth,
                Gender = user.GenderId,
                Nickname = user.Nickname!,
                PersonalSignature = user.PersonalSignature!,
                UserName = user.UserName
            };
            ViewBag.Title = "我的信息";
            return View(model);
        }

        [Authorize]
        [HttpPost("{controller}/setting/{action}")]
        public async Task<IActionResult> Info(SpaceSettingInfoViewModel model)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            user.Nickname = model.Nickname;
            user.PersonalSignature = model.PersonalSignature;
            user.GenderId = model.Gender;
            user.Birth = model.Birth;
            _campusDbContext.Update<AppUser>(user);
            _campusDbContext.SaveChanges();
            return RedirectToAction("SpaceBase");
        }

        [Authorize]
        [HttpGet("{controller}/setting/{action}")]
        public async Task<IActionResult> Face()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var model = new SpaceSettingFaceViewModel
            {
                HeadPortrait = user.HeadPortrait!
            };
            ViewBag.Title = "我的头像";
            return View(model);
        }

        [Authorize]
        [Route("{controller}/setting/{action}")]
        [HttpPost]
        public async Task<IActionResult> Face(SpaceSettingFaceViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                // 判断文件类型
                string fileType = model.File.FileName.Substring(model.File.FileName.LastIndexOf(".")).ToLower();
                if (fileType == ".jpg" || fileType == ".png" || fileType == ".gif")
                {
                    if (model.File.Length > (1024 * 1024 * 2))
                    {
                        ModelState.AddModelError(string.Empty, "图片需小于2M");
                        return View(model);
                    }
                    // 将图片上传到wwwroot的images文件夹中
                    // 获取wwwroot的路径
                    string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                    if (System.IO.Directory.Exists(uploadFolder) == false)//如果不存在就创建file文件夹
                    {
                        System.IO.Directory.CreateDirectory(uploadFolder);
                    }
                    // 确保文件名字唯一
                    uniqueFileName = Guid.NewGuid() + fileType;
                    string filePath = Path.Combine(uploadFolder, uniqueFileName);
                    // 使用IFormFile接口的CopyTo()方法
                    model.File.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "文件类型只支持JPG、PNG、GIF格式");
                    return View(model);
                }
                var user = await _userManager.GetUserAsync(HttpContext.User);
                user.HeadPortrait = "/images/" + uniqueFileName;
                _campusDbContext.Update(user);
                _campusDbContext.SaveChanges();
                return RedirectToAction("SpaceBase");
            }
            return View(model);
        }

        [Authorize]
        [HttpGet("{controller}/setting/{action}")]
        public async Task<IActionResult> Account()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var model = new SpaceSettingFaceViewModel
            {
                HeadPortrait = user.HeadPortrait!
            };
            ViewBag.Title = "我的头像";
            return View(model);
        }
        [Authorize]
        [HttpGet("{controller}/{action}")]
        public async Task<IActionResult> FollowList(string id)
        {
            ViewBag.title = "全部关注";
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return View("NotFound");
            }
            return View("FollowList", user.Follows.Select((u) => new
            {
                Id = u.TargetId,
                PersonalSignature = u.Target.PersonalSignature,
                HeadPortrait = u.Target.HeadPortrait,
                Nickname = u.Target.Nickname
            }).ToList());
        }
        [Authorize]
        [HttpGet("{controller}/{action}")]
        public async Task<IActionResult> FollowListBtn(string id)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var follow = _campusDbContext.Follows
            .FirstOrDefault(f => f.UserId == user.Id && f.TargetId == id);
            if (follow == null)
            {
                _campusDbContext.Follows.Add(new Follow
                {
                    TargetId = id,
                    UserId = user.Id
                });
            }
            else
            {
                _campusDbContext.Follows.Remove(follow);
            }
            _campusDbContext.SaveChanges();
            return Content("true");
        }
        [Authorize]
        [HttpGet("{controller}/{action}")]
        public async Task<IActionResult> FansList(string id)
        {
            ViewBag.title = "全部粉丝";
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return View("NotFound");
            }
            return View("FollowList", user.Targets.Select((u) => new
            {
                Id = u.UserId,
                PersonalSignature = u.User.PersonalSignature,
                HeadPortrait = u.User.HeadPortrait,
                Nickname = u.User.Nickname
            }).ToList());
        }
        [Authorize]
        [HttpGet("{controller}/{action}")]
        public async Task<IActionResult> ComplainsList()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var model = _campusDbContext.Opinions.Where(o => o.UserId == user.Id).ToList();
            return View(model);
        }
        [Authorize]
        [HttpGet("{controller}/{action}")]
        public async Task<IActionResult> Opinion(int id)
        {
            var model = await _campusDbContext.Opinions.FirstOrDefaultAsync(o => o.OpinionId == id);
            if (model == null)
            {

Campus/Views/Platform/CollectionView.cshtml
@section style{
    <link rel="stylesheet" href="~/css/collections.css">
}

@model IEnumerable<Campus.Models.Collection>
<div id="collection_Body">
	<div id="collection_Head">
				全部收藏
			</div>
@foreach (var item in Model)
	{
			<div class="collection">
				<div class="collection_BT">
					@(item.Works.Title.Length <=20?item.Works.Title:item.Works.Title.Substring(0,20)+"...")
				</div>
				<div class="collection_NR">
					@(item.Works.DisplayContent.Length <=40?item.Works.DisplayContent:item.Works.DisplayContent.Substring(0,40)+"...")
				</div>
				<div class="collection_R">
					<span><img src="@item.Works.User.HeadPortrait">@item.Works.User.Nickname</span>	
				</div>
				<div class="collection_Button" >
					<input type="button" value="取消收藏" onclick="CollectionBtn(@item.WorksId,this)" >	
				</div>
			</div>
	}
		</div>

		@section script{
    <script>
        function CollectionBtn(work,o) {
            $.ajax({
                url: "/platform/CollectionBtn?id=" + work,
                data: {
					
                },
                success: function(res) {
                    var test = $(o).val();
                    if (test == "取消收藏") {
                        $(o).val("收藏");
                    } else {
                        $(o).val("取消收藏");
                    }  
                }
            })
        }

    </script>
}

Campus/Views/Platform/Comments.cshtml
@model CommentViewModel

<div id="post_PL_head">
            @Model.Comments.Count()评论
        </div>
        <div id="post_PL_NR">
            <span><img src="@Model.HeadPortrait" asp-append-version></span><span>
                <textarea cols="90" rows="4"
                      class="text"></textarea>
            </span><span><input type="button" id="button" value="提交评论" onclick="submitComment(@Model.WorksId)"></span>
        </div>

        @foreach (var comment in Model.Comments)
        {
            <div class="post_PL_PLNR">
                <div>
                    <img src="@comment.User.HeadPortrait" asp-append-version>
                    <div>
                        <div class="post_PL_PLNR_name">@comment.User.Nickname</div>
                        <div class="post_PL_PLNR_nr">@comment.Content</div>
                        <div class="post_PL_PLNR_nr">
                            <span>@comment.ReleaseTime</span>&nbsp;&nbsp;&nbsp;
                            <span>点赞(@comment.Like)</span>&nbsp;&nbsp;&nbsp;
                            <span class="speak_back">回复 @comment.Comments.Count()</span>&nbsp;&nbsp;&nbsp;<span>举报</span>
                        </div>
                        <div>
                            <div id="post_PL_NR1">
                                <span><img src="@Model.HeadPortrait" asp-append-version></span>
                                <span  class="textarea">
                                    <textarea name="" id="" cols="80" rows="3"
                                      class="text2"></textarea>
                                </span><span>
                                <input type="button" id="button2" value="提交评论" onclick="sencoud_submitComment(@comment.CommentId,@Model.WorksId,this)">
                                </span>
                            </div>
                            @foreach (var secondComment in comment.Comments)
                            {
                                <div class="second_comment">
                                    <img src="@secondComment.User.HeadPortrait" alt="">
                                    <div>
                                        <div class="post_PL_PLNR_name">@secondComment.User.Nickname</div>
                                        <div class="post_PL_PLNR_nr">@secondComment.Content</div>
                                        <div class="post_PL_PLNR_nr">
                                            <span>@secondComment.ReleaseTime</span>&nbsp;&nbsp;&nbsp;<span>点赞(@secondComment.Like)</span>&nbsp;&nbsp;&nbsp;<span>举报</span>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
        @section script{
            <script src="~/lib/read.js"></script>
            <script type="text/javascript" src="~/lib/qrcode.min.js" asp-append-version="true"></script>
            <script>
                $('.speak_back').click(function () {
	$(this).parent().siblings('div:last-child').toggle()
})
            </script>
        }

Campus/Views/Platform/Manage.cshtml
@model IEnumerable<WorksManage>
@{
	Layout = null;
}
<link rel="stylesheet" href="~/css/postManage.css" asp-append-version="true">

<div class="homepage">

	@foreach (var worksManage in Model)
	{
		<div class="manuscript-div">
			<div class="manuscript">
				<div class="img-box"><img src="@worksManage.Img" asp-append-version></div>
				<div class="content">
					<div class="Plate-1">
						<span class="Label-type">@worksManage.SpecialColumnValue</span><span>
							<a asp-action="Read" asp-route-id="@worksManage.EncryptedId"
						   style="margin-left:12px ;font-size: 20px;">
								@worksManage.Title
							</a>
						</span>
					</div>
					<div class="Plate-2"><span>@worksManage.DisplayContent</span></div>
					<div class="Plate-3"><span>发布时间：<span>@worksManage.ReleaseTime</span></span></div>
					<div class="Plate-4">
						<div style="width:90%;">
							<span>
								👀&nbsp;&nbsp;<span>@worksManage.Browse</span>
							</span>
							<span>
								🗨&nbsp;&nbsp;<span>@worksManage.CommentCount</span>
							</span>
							<span>
								⭐&nbsp;&nbsp;<span>@worksManage.CollectionCount</span>
							</span>
							<span>
								👍&nbsp;&nbsp;<span>@worksManage.FabulouCount</span>
							</span>
						</div>
						<div class="delete"><button onclick="DeleteMyWorks('@worksManage.EncryptedId')">删除</button></div>
					</div>
				</div>
			</div>
		</div>
	}
</div>
<script>
	function DeleteMyWorks(id) {
		if (confirm('你真的要删除吗？')) {
			$.ajax({
				url: "/Platform/DeleteMyWorks",
				data: {
					id: id
				},
				method: "Get",
				success: function(res) {
					$("#content").html(res);
				}
			})
		}
	}
</script>

Campus/Views/Platform/Read.cshtml
@using Campus.Models
@model PlatformReadViewModel
@inject SignInManager<AppUser> _signInMamager
@inject UserManager<AppUser> _userManager

@{
    ViewBag.Title = "文章详情";
    var isSignIn = _signInMamager.IsSignedIn(User);
    AppUser user = null;
    if (isSignIn) user = await _userManager.GetUserAsync(User);
}
@section style{
    <link rel="stylesheet" asp-append-version="true" href="~/css/shoolps.css">
    <style type="text/css">
        #ad {
            width: 278px;
            height: 188px;
            position: fixed;
            right: 0px;
            bottom: 0px;
            background: url(img/ad.jpg) no-repeat;
            display: none;
        }

            #ad span {
                font-size: 20px;
                cursor: pointer;
            }
    </style>
}
    <div id="School_Head">
        <div id="School_Head_ul">
            <ul>
                <li><a href="#">校园简介</a></li>
                <li>|</li>
                <li><a asp-action="CampusWorld" asp-controller="Home">校园天地</a></li>
                <li>|</li>
                <li><a href="#">校园风景</a></li>
                <li>|</li>
                <li><a href="#">国家新闻</a></li>
                <li>|</li>
                <li><a href="#">学生论坛</a></li>
            </ul>
        </div>
        <div id="School_Head_people">
            <ul>
                <li><a href="#">意见箱</a></li>
            </ul>
        </div>
    </div>
    <div id="sch_Post_head"><span>@Model.SpecialColumnValue</span><span>/</span><span>@Model.Title</span></div>
    <div id="good">
        @if (isSignIn)
    {
        
        @if (Model.GoodButton)
            {
                <div id="good1" ><img src="~/img/good_2.png" class="good1" asp-append-version onclick="SubmitFabulous(@Model.WorksId)"/></div>
            }
            else
            {
                <div id="good1" ><img src="~/img/good_1.png" class="good1" asp-append-version onclick="SubmitFabulous(@Model.WorksId)"/></div>
            }
        
        
            @if (Model.CollectionButton)
            {
                <div id="good2" ><img src="~/img/mine_2.png" class="good2" asp-append-version onclick="SubmitCollection(@Model.WorksId)"/></div>
            }
            else
            {
                <div id="good2" ><img src="~/img/mine_1.png" class="good2" asp-append-version onclick="SubmitCollection(@Model.WorksId)"/></div>

            }
       
    }
    <div id="good3"><img src="~/img/gouse_2.png" class="good3" /></div>
    <a asp-action="index" asp-controller="Home"><div id="good4"><img src="~/img/index_2.png" style="width:35px;height:35px" /></div></a>
</div>
<div id="Post_first">
    <div id="Post_first_head">
        <div id="Post_first_head_BT">
            @Model.Title
            <div id="post_first_div1">
                <span>@Model.SpecialColumnValue</span>
                <span>时间：@Model.ReleaseTime</span>
                <span>@Model.Browse 阅读</span>
                <span>@Model.FabulousNum 点赞</span>
                <span>@Model.Comments.Count() 评论</span>
            </div>
        </div>
        <div id="post_sch_people">
            <a href="/space/@Model.User.Id">
                <img src="@Model.User.HeadPortrait" asp-append-version>
            </a>
            <span>@Model.Nickname</span>
            <p><span>粉丝：</span><span>@Model.TargetsNum</span></p>

            @if (Model.FollowButton)
            {
                <div id="post_guanzhu">+关注</div>
            }
        </div>
    </div>
    <div id="post_center">
        <div id="post_center_NR">
            <div id="post_center_NR_wz">
                @Html.Raw(Model.Content)
            </div>
            <div id=""><a asp-action="AddComplains" asp-controller="Home" asp-route-id="@Model.WorksId">举报</a></div>
        </div>
    </div>

</div>
@if (isSignIn)
{
    <div id="post_PL">
        <div id="post_PL_head">
            @Model.Comments.Count()评论
        </div>
        <div id="post_PL_NR">
            <span><img src="@user.HeadPortrait" asp-append-version></span><span>
                <textarea cols="90" rows="4"
                      class="text"></textarea>
            </span><span><input type="button" id="button" value="提交评论" onclick="submitComment(@Model.WorksId)"></span>
        </div>

        @foreach (var comment in Model.Comments)
        {
            <div class="post_PL_PLNR">
                <div>
                    <img src="@comment.User.HeadPortrait" asp-append-version>
                    <div>
                        <div class="post_PL_PLNR_name">@comment.User.Nickname</div>
                        <div class="post_PL_PLNR_nr">@comment.Content</div>
                        <div class="post_PL_PLNR_nr">
                            <span>@comment.ReleaseTime</span>&nbsp;&nbsp;&nbsp;
                            <span>点赞(@comment.Like)</span>&nbsp;&nbsp;&nbsp;
                            <span class="speak_back">回复 @comment.Comments.Count()</span>&nbsp;&nbsp;&nbsp;<span>举报</span>
                        </div>
                        <div>
                            <div id="post_PL_NR1">
                                <span><img src="@Model.MyHeadPortrait" asp-append-version></span>
                                <span class="textarea">
                                    <textarea name="" id="" cols="80" rows="3"
                                      class="text2"></textarea>
                                </span>
                                <span>
                                    <input type="button" id="button2" value="提交评论" onclick="sencoud_submitComment(@comment.CommentId,@Model.WorksId,this)">
                                </span>
                            </div>
                            @foreach (var secondComment in comment.Comments)
                            {
                                <div class="second_comment">
                                    <img src="@secondComment.User.HeadPortrait" alt="">
                                    <div>
                                        <div class="post_PL_PLNR_name">@secondComment.User.Nickname</div>
                                        <div class="post_PL_PLNR_nr">@secondComment.Content</div>
                                        <div class="post_PL_PLNR_nr">
                                            <span>@secondComment.ReleaseTime</span>&nbsp;&nbsp;&nbsp;<span>点赞(@secondComment.Like)</span>&nbsp;&nbsp;&nbsp;<span>举报</span>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

}

<div id="ad">
    <span>&times;</span>
</div>
@section script{
    <script src="~/lib/read.js"></script>
    <script type="text/javascript" src="~/lib/qrcode.min.js" asp-append-version="true"></script>
    <script>
        $(function() {
            var qrcode = new QRCode(document.getElementById("ad"), {
                text: window.location.href,
                width: 128,
                height: 128,
                colorDark: "#f60",
                colorLight: "#ccc",
                correctLevel: 0 // 二维码结构复杂性 0~3
            });

            $("#good3").click(function() {
                //弹窗广告
                $("#ad").slideToggle(800);
            })
            $("#ad span").click(function() {
                //关闭弹窗广告
                $("#ad").slideToggle(800);
            })

            $("#post_guanzhu").click(function() {
                $.ajax({
                    url: "/platform/Follow",
                    data: {
                        id: '@Model.User.Id'
                    },
                    success: function(res) {
                        $("#post_guanzhu").hide();
                    }
                })
            })
        })
        function submitComment(wid) {
            $.ajax({
                url: "/platform/submitComment?id=" + wid,
                data: { text: '' + $(".text").val() },
                success: function(res) {
                    $("#post_PL").html(res);
                }
            })
        }
        function sencoud_submitComment(pid, wid, o) {
            $.ajax({
                url: "/platform/submitComments?id=" + pid,
                data: {
                    text2: o.parentNode.previousElementSibling.firstElementChild.value,
                    works: wid
                },
                success: function(res) {
                    $(o).parent().parent().parent().html(res);
                }
            })
        }
        function SubmitCollection(id) {
            $.ajax({
                url: "/platform/SubmitCollection?id=" + id,
                data: {

                },
                success: function(res) {

                }
            })
        }
        function SubmitFabulous(id) {
            $.ajax({
                url: "/platform/SubmitFabulous?id=" + id,
                data: {

                },
                success: function(res) {

                }
            })
        }
    </script>
}

Campus/Views/Platform/Upload.cshtml
@model PlatformUploadViewModel
@{
	ViewBag.Title = "投稿";
}

@section style{
	<link rel="stylesheet" href="~/css/sendpost/post.css" asp-append-version="true">
	<link href="~/lib/summernote-0.8.12/dist/summernote.css" rel="stylesheet" asp-append-version="true">
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">
	<style>
		* {
			user-select: none
		}
	</style>
}
	<div id="post-body">
		<div class="post-head">
			<div class="post-logo"><img src="~/img/sendpost/logo.png" style="height: 100%;width:75%;opacity: 0.8;"></div>
			<div class="post-tx">
				<span>
					<a asp-action="" asp-controller="Space">
						<img asp-append-version src="@Model.HeadPortrait" style="width: 100%;height: 100%;border-radius: 50%;">
					</a>
				</span>
			</div>
		</div>
		<div class="post-connect">
			<div class="post-ul">
				<ul class="pul">
					<li id="lia" style="background-color: rgb(161, 221, 234);color: black;">投稿</li>
					<li id="WorksManage">稿件管理</li>
					<li id="Guit">稿件指南</li>
				</ul>
			</div>
			<div class="post-bit" id="content">
				<form method="post" style="height:100%;width: 100%;">
					<input asp-for="HeadPortrait" type="hidden" />
					<div class="panel panel-default" style="height:100%;width: 100%;">
						<div class="panel-body">
							<div class="form-group">
								<label asp-for="Title"></label>
								<input asp-for="Title" class="form-control">
								<span asp-validation-for="Title"></span>
							</div>
							<label asp-for="Content"></label>
							<textarea asp-for="Content" id="summernote"></textarea>
							<span asp-validation-for="Content"></span>
							<div class="post-type">
								<p style="font-size: 10px;">请选择话题</p>
								<ul class="tul">
									@for (int i = 0; i < Model.SpecialColumns!.Count; i++)
								{
									<li>
										<input asp-for="SpecialColumnId" type="radio" checked="@(i==0)" value="@Model.SpecialColumns[i].SpecialColumnId" />
										@Model.SpecialColumns[i].SpecialColumnValue
									</li>
								}

							</ul>
						</div>
						<div class="form-group text-right" style="margin-top:20px">
							@*<button type="button" class="btn btn-default">保存草稿</button>*@
							<input type="submit" value="发布"
								   class="btn btn-primary" style="background-color: #6699CC;" />
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

@section script{
	<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="~/lib/summernote-0.8.12/dist/summernote.js"></script>
	<script src="~/lib/summernote-0.8.12/dist/lang/summernote-zh-CN.js"></script>
	<script>
		$(function() {
			$('#summernote').summernote({
				height: 215,                 // set editor height
				minHeight: 215,             // set minimum height of editor
				maxHeight: 215,              // set maximum height of editor
				focus: true,                 // set focus to editable area after initializing summernote
				lang: 'zh-CN',               // default: 'en-US'
				callbacks: {
					onImageUpload: function(files) {
						sendFile(files[0]);
					}
				}
			});
			$('#lia').click(function() {
				window.location = '/Platform/Upload';
			})
			$('#WorksManage').click(function() {
				$.ajax({
					url: "/Platform/Manage",
					method: "Get",
					success: function(res) {
						$("#content").html(res);
					}
				})
			})
		});
		function sendFile(file) {
			data = new FormData();
			data.append("file", file);
			$.ajax({
				data: data,
				type: "POST",
				url: "/platform/uploadimage",
				cache: false,
				contentType: false,
				processData: false,
				success: function(url) {
					console.log(url)
					$('#summernote').summernote('insertImage', url, function($image) {
						$image.attr('src', url);
					});
				}
			});
		}
		$("#WorksManage").click(function() {
			$(this).css("background-color", "rgb(161, 221, 234)")
			$(this).css("color", "black")
			$("#lia").css("background-color", "#666699")
			$("#lia").css("color", "white")
			$("#Guit").css("background-color", "#666699")
			$("#Guit").css("color", "white")
			
		})
		$('#Guit').click(function() {
			$(this).css("background-color", "rgb(161, 221, 234)")
			$(this).css("color", "black")
			$("#lia").css("background-color", "#666699")
			$("#lia").css("color", "white")
			$("#WorksManage").css("background-color", "#666699")
			$("#WorksManage").css("color", "white")
			$.ajax({
				url: "/Platform/Submission_Guide",
				method: "Get",
				success: function(res) {
					$("#content").html(res);
				}
			})
		})
	</script>
	}